out_dir: slam_output

odometry:
  data:
    deskew: true
    max_range: 50.0
    min_range: 0.0 
  adaptive_threshold:
    initial_threshold: 2.0
    min_motion_th: 0.1
  registration:
    convergence_criterion: 0.0001
    max_num_iterations: 500
    max_num_threads: 0
  mapping:
    max_points_per_voxel: 20
    voxel_size: 0.5

local_mapper:
  voxel_size: 0.5
  splitting_distance: 100.0
